version: 2
updates:
  - package-ecosystem: github-actions
    directory: ".github"
    groups:
      all-dependencies:
        patterns:
          - "*"
    schedule:
      interval: weekly
      time: "08:00"
      timezone: "Australia/Melbourne"
    open-pull-requests-limit: 1
